name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  host_port:
    description: "Docker Port"
    default: "22"
    required: false
  host_username:
    description: "Docker User"
    required: true
  host_password:
    description: "Docker Pass"
    required: false
  registry:
    description: "Container registry to use"
    required: false
    default: ""
  username:
    description: "Container registry username"
    required: false
    default: ""
  password:
    description: "Container registry password"
    required: false
    default: ""
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
